ARCH: Added basic model validations with room for Active storage for …
amanianai/covid-conscious pull request #1
Opened 2020-12-01 04:04 UTC by friendlyantz

# Pull Request
		
## Description :speak_no_evil:

MODEL validations
		
## Changes :octopus:
- [x] **users** 
- [x] **locations**
- [x] **places**
- [x] **reviews**: 
		
## How Has This Been Tested? :microscope:
- [x] Inspection

2020-12-01 04:30 UTC, rycmak requested changes
`review.rb:`
`belongs_to :place` (singular)
`belongs_to :user` (singular)

user.rb:
I think user `has_one :location`, while location `belongs_to :user`?

2020-12-01 05:14 UTC, friendlyantz commented
> `review.rb:`
> `belongs_to :place` (singular)
> `belongs_to :user` (singular)
> 
> `user.rb`:
> I think user `has_one :location`, while location `belongs_to :user`?

corrected plural typos, 

Re user.rb - has_many is the only option, not has_one

2020-12-01 07:38 UTC, friendlyantz commented
struggling with reviews seed / model

2020-12-02 03:35 UTC, rycmak approved these changes

2020-12-02 03:35 UTC, merged